import { IUser } from "src/app/interfaces/user";


export const USERS: IUser[] = [
    {
        id:"user1",
        userName:"test1",
        displayUsername: '',
        profileBackgroundUrl: '',
        email:"test1@expa.com",
        profilePictureUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwuv23w6aRvepgjHa9wEpbmhTZ_CMiV5jUwecYldQ&s",
        posts:[],
        comments: [],
        postLikes: [],
        commentLikes: [],
        followers: [],
        followedUsers: [],
        individualChats: [],
        groupChats: [],
        individualChatMessages: [],
        dateRegistrated: new Date(),
        groupChatMessages: [],
        notifications: []
      },
      {
        id:"user2",
        userName:"test2",
        displayUsername: '',
        profileBackgroundUrl: '',
        email:"test2@expa.com",
        profilePictureUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwuv23w6aRvepgjHa9wEpbmhTZ_CMiV5jUwecYldQ&s",
        posts:[],
        comments: [],
        postLikes: [],
        commentLikes: [],
        followers: [],
        followedUsers: [],
        individualChats: [],
        groupChats: [],
        individualChatMessages: [],
        groupChatMessages: [],
        dateRegistrated: new Date(),
        notifications: []
      },
      {
        id:"user3",
        userName:"test3",
        displayUsername: '',
        profileBackgroundUrl: '',
        email:"test3@expa.com",
        profilePictureUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwuv23w6aRvepgjHa9wEpbmhTZ_CMiV5jUwecYldQ&s",
        posts:[],
        comments: [],
        postLikes: [],
        commentLikes: [],
        followers: [],
        followedUsers: [],
        dateRegistrated: new Date(),
        individualChats: [],
        groupChats: [],
        individualChatMessages: [],
        groupChatMessages: [],
        notifications: []
      },
      {
        id:"user4",
        userName:"test4",
        displayUsername: '',
        profileBackgroundUrl: '',
        email:"test4@expa.com",
        profilePictureUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwuv23w6aRvepgjHa9wEpbmhTZ_CMiV5jUwecYldQ&s",
        posts:[],
        dateRegistrated: new Date(),
        comments: [],
        postLikes: [],
        commentLikes: [],
        followers: [],
        followedUsers: [],
        individualChats: [],
        groupChats: [],
        individualChatMessages: [],
        groupChatMessages: [],
        notifications: []
      }
];